services:
  tiny_lobby:
    build: .
    container_name: tiny_lobby
    platform: linux/amd64
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./config.ini:/app/config.ini
      - ./logs:/app/logs
