services:
  lobby_server:
    build: .
    container_name: lobby_server
    platform: linux/amd64
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    ports:
      - "8080:8080"
    restart: unless-stopped
