name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install clang-format and clang-tidy
        run: |
          sudo apt-get update
          sudo apt-get install clang-format clang-tidy

      - name: Check formatting in src directory
        run: ./check_format.sh

  build:
    needs: lint
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform: [{
              os: ubuntu-latest,
              arch: x64
            }, 
            {
              os: windows-latest,
              arch: x64
            }, 
            {
            os: macos-latest,
            arch: x64
            }, 
            {
            os: macos-latest,
            arch: arm64
            }
              ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    
    - name: Print versions
      shell: bash
      if: matrix.platform.os == 'ubuntu-latest' || matrix.platform.os == 'macos-latest'
      run: |
        cmake --version
        clang --version

    - name: Build & Install dependencies for Linux
      if: matrix.platform.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install -y software-properties-common
        ./install-linux.sh
        ./build_release.sh

    - name: Build & Install dependencies for macOS arm64
      if: matrix.platform.os == 'macos-latest' && matrix.platform.arch == 'arm64'
      run: |
        ./install-macos-arm64.sh
        ./build_release_macos-arm64.sh

    - name: Build & Install dependencies for macOS x64
      if: matrix.platform.os == 'macos-latest' && matrix.platform.arch == 'x64'
      run: |
        ./install-macos-x64.sh
        ./build_release_macos-x64.sh
    
    - name: Build & Install dependencies for Windows
      shell: cmd
      if: matrix.platform.os == 'windows-latest'
      run: |
        .\install-windows.ps1

        # Run build_release.bat
        .\build_release.ps1

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lobby_server-${{ matrix.platform.os }}-${{ matrix.platform.arch }}
        path: |
          build/lobby_server*
        if-no-files-found: error
