name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: ["*"]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint Code (Ubuntu)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install clang-format and clang-tidy
        run: |
          sudo apt-get update
          sudo apt-get install clang-format clang-tidy

      - name: Check formatting in src directory
        run: ./check_format.sh
      
      - name: Download luau-analyze
        run: |
          wget https://github.com/luau-lang/luau/releases/download/0.667/luau-ubuntu.zip
          unzip luau-ubuntu.zip
          chmod +x luau-analyze
          ./luau-analyze scripts/**/*.lua

  build-linux:
    name: Build on Linux (${{ matrix.arch }} ${{ matrix.type }})
    needs: lint
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        arch: [x64, arm64]
        type: [release] #[debug, release]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      
      - name: Cache vcpkg dependencies
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cache/vcpkg
            external/vcpkg/installed
          key: vcpkg-${{ runner.os }}-${{ matrix.arch }}-${{ matrix.type }}
      
      - name: Create Public Key
        run: |
          echo "${{ secrets.PUBLIC_KEY }}" > public.key

      - name: Print versions
        run: |
          cmake --version
          clang --version

      - name: Install dependencies ${{ matrix.arch }}
        run: |
          sudo apt update
          sudo apt install -y software-properties-common autoconf 
          ./install-linux-${{ matrix.arch }}.sh

      - name: Cache vcpkg dependencies
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.cache/vcpkg
            external/vcpkg/installed
          key: vcpkg-${{ runner.os }}-${{ matrix.arch }}-${{ matrix.type }}

      - name: Build Release
        run: |
          ./build_${{ matrix.type }}-${{ matrix.arch }}.sh

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lobby_server-linux-${{ matrix.arch }}-${{ matrix.type }}
          path: build/lobby_server
          if-no-files-found: error

  test:
    name: Test Code (Ubuntu)
    runs-on: ubuntu-22.04
    needs: build-linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download Linux build artifact
        uses: actions/download-artifact@v4
        with:
          name: lobby_server-linux-x64-release
          path: build
      
      - name: Clone Old Lobby Server
        uses: actions/checkout@v4
        with:
          repository: blazium-engine/blazium-lobby
          path: old-lobby
          token: ${{ secrets.GH_PAT }}
      
      # Set up Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21  # Specify the Go version you are using

      # Install dependencies
      - name: Install Dependencies
        working-directory: old-lobby
        run: go mod tidy

      # Run the app and tests in the same step
      - name: Run App and Tests
        working-directory: old-lobby
        run: |
          # Start the app in the background
          cd ..
          cp build/lobby_server .
          ls
          chmod +x lobby_server
          ./lobby_server --disable-login &> app.log &
          sleep 10
          cd old-lobby
          go test -timeout 200s -tags=auth ./... -v
          go test -timeout 200s -tags=lobby ./... -v
      
      # Always print server logs
      - name: Print Server Logs
        if: always()
        run: |
          cat app.log
          cat logs/game.txt
          cat logs/websocket.txt

  build-macos:
    name: Build on macOS (${{ matrix.arch }})
    needs: lint
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        arch: [x64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      
      - name: Cache vcpkg dependencies
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cache/vcpkg
            external/vcpkg/installed
          key: vcpkg-${{ runner.os }}-${{ matrix.arch }}
      
      - name: Create Public Key
        run: |
          echo "${{ secrets.PUBLIC_KEY }}" > public.key

      - name: Print versions
        run: |
          cmake --version
          clang --version

      - name: Install dependencies (macOS)
        run: |
          ./install-macos-${{ matrix.arch }}.sh

      - name: Cache vcpkg dependencies
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.cache/vcpkg
            external/vcpkg/installed
          key: vcpkg-${{ runner.os }}-${{ matrix.arch }}
  
      - name: Build (macOS)
        run: |
          ./build_release_macos-${{ matrix.arch }}.sh

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lobby_server-macos-${{ matrix.arch }}
          path: build/lobby_server*
          if-no-files-found: error

  build-windows:
    name: Build on Windows (x64)
    needs: lint
    if: false
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: ilammy/msvc-dev-cmd@v1.4.1
      
      - name: Cache vcpkg dependencies
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cache/vcpkg
            external/vcpkg/installed
          key: vcpkg-${{ runner.os }}

      - name: Create Public Key
        run: |
          echo "${{ secrets.PUBLIC_KEY }}" > public.key

      - name: Install dependencies
        shell: pwsh
        run: |
          .\install.ps1

      - name: Cache vcpkg dependencies
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.cache/vcpkg
            external/vcpkg/installed
          key: vcpkg-${{ runner.os }}

      - name: Install RNP
        shell: pwsh
        run: |
          .\install-rnp.ps1

      - name: Build Release
        shell: pwsh
        run: |
          .\build_release.ps1

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lobby_server-windows-x64
          path: build/lobby_server*
          if-no-files-found: error
  
  docker-build:
    name: Build Docker Image (Linux)
    needs: [build-linux, test]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: registry.digitalocean.com
      REGISTRY_PATH: blazium-registry
      DOCKER_NAME: lobby_server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download Linux build artifact
        uses: actions/download-artifact@v4
        with:
          name: lobby_server-linux-x64-release
          path: build/      

      - name: List contents of build directory
        run: ls -R build
        
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            GITHUB_SHA=${{ github.sha }}
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.REGISTRY_PATH }}/${{ env.DOCKER_NAME }}:latest
            ${{ env.DOCKER_REGISTRY }}/${{ env.REGISTRY_PATH }}/${{ env.DOCKER_NAME }}:${{ github.sha }}  
