name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install clang-format and clang-tidy
        run: |
          sudo apt-get update
          sudo apt-get install clang-format clang-tidy

      - name: Check formatting in src directory
        run: ./check_format.sh

  build:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    
    - name: Print versions
      shell: bash
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: |
        cmake --version
        clang --version

        cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON . CMakeCache.txt
        cat CMakeCache.txt

    - name: Build & Install dependencies for Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install -y software-properties-common
        ./install-linux.sh
        ./build_release.sh

    - name: Build & Install dependencies for macOS ARM64
      if: matrix.os == 'macos-latest'
      run: |
        ./install-macos-arm64.sh
        ./build_release_macos-arm64.sh

    
    - name: Build & Install dependencies for Windows
      shell: cmd
      if: matrix.os == 'windows-latest'
      run: |
        .\install-windows.ps1

        # Run build_release.bat
        .\build_release.ps1

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-lobby_server
        path: |
          build/lobby_server*
        if-no-files-found: error
